version: '3.4'

services:
  andon-webapp-in-go:
    build: ./
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./webapp
        target: /app
    environment:
      - STATIC_ROOT=../static
      - VIEW_ROOT=../views
      - ENV=development
      - salt=${salt}
    command: ["go", "run", "."]
  e2e:
    build:
      context: ./webapp
      dockerfile: Dockerfile.e2e
    volumes:
      - type: bind
        source: ./webapp
        target: /app
    environment:
      - ENV=test
      - STATIC_ROOT=../../static
      - VIEW_ROOT=../../views
      - salt=${salt}
    command: ["go", "test", "./e2e", "-test.v"]
  db:
    image: postgres:12.3-alpine
    volumes: 
      - db-data:/var/lib/postgresql/db-data
      - type: bind
        source: ./db/init #initial scripts to be run when volume is brought for first time
        target: /docker-entrypoint-initdb.d 
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
volumes: 
    db-data:




    
